# pickle形式

## pickleの注意点

In [1]:
import pickle
import pandas as pd

In [2]:
df = pd.read_csv(
    "data/FEH_00200524_230205124938.csv",
    encoding="cp932",
    parse_dates=["時間軸（年月日現在）"],
    date_format="%Y年%m月",
    thousands=",",
)
df.head()

     表章項目   人口  概算値  全国 時間軸（年月日現在）  年齢5歳階級  /男女別    男女計     男     女
0  人口【万人】  総人口  概算値  全国 2021-12-01      総数   NaN  12547  6099  6448
1  人口【万人】  総人口  概算値  全国 2021-12-01    0～4歳   NaN    437   224   214
2  人口【万人】  総人口  概算値  全国 2021-12-01    5～9歳   NaN    503   258   245
3  人口【万人】  総人口  概算値  全国 2021-12-01  10～14歳   NaN    535   274   261
4  人口【万人】  総人口  概算値  全国 2021-12-01  15～19歳   NaN    559   287   272

In [3]:
with open("data/csv-to-pickle.pickle", "wb") as f:  # ・・①
    pickle.dump(df, f)  # ・・②

In [4]:
with open("data/csv-to-pickle.pickle", "rb") as f:  # ・・③
    df_loaded = pickle.load(f)  # ・・④

In [5]:
df_loaded.head(2)

     表章項目   人口  概算値  全国 時間軸（年月日現在） 年齢5歳階級  /男女別    男女計     男     女
0  人口【万人】  総人口  概算値  全国 2021-12-01     総数   NaN  12547  6099  6448
1  人口【万人】  総人口  概算値  全国 2021-12-01   0～4歳   NaN    437   224   214

In [6]:
df_loaded.dtypes

表章項目                  object
人口                    object
概算値                   object
全国                    object
時間軸（年月日現在）    datetime64[ns]
年齢5歳階級                object
/男女別                 float64
男女計                    int64
男                      int64
女                      int64
dtype: object

In [7]:
df.to_pickle("data/df-to-pickle.pickle")

In [8]:
df_loaded2 = pd.read_pickle("data/df-to-pickle.pickle")

In [9]:
df_loaded2.head(2)

     表章項目   人口  概算値  全国 時間軸（年月日現在） 年齢5歳階級  /男女別    男女計     男     女
0  人口【万人】  総人口  概算値  全国 2021-12-01     総数   NaN  12547  6099  6448
1  人口【万人】  総人口  概算値  全国 2021-12-01   0～4歳   NaN    437   224   214